spring.application.name=back-end

spring.datasource.url=jdbc:mysql://localhost:3306/individual3sptech
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=eventos
spring.datasource.password=Eventos#1234